### PR TITLE
Fix #28, fix ShortString constructor

### LINKED ISSUE #28: Access violations due to code converting String types to ShortString
I'll make a PR for this, but what is going on is that instead of using the intended size of the ShortString for the pointer size to load, it needs to use the size of the string (or substring) being loaded, and also start at the beginning of a aligned block.
A String will always start off aligned on a sizeof(UInt)*2 boundary (i.e. 8 or 16 bytes) + sizeof(UInt) (the size is stored in the first 4 or 8 bytes).
A SubString{String} could start off anywhere.

For a first pass, I can write something that loads strings pretty quickly, especially for String (SubString requires a bit more work), using a loop that loads aligned 4 or 8 byte chunks, and later optimize further for cases that can be done with a single load safely.

### PR DESCRIPTION
**Pull request by ScottPJones**
This fixes the access violations that ZJ had seen, where the unsafe_load was trying to access past the end of allocated memory.
Currently, it just does the loading a byte at a time for `SubString{String}`, but that will be fixed in a later PR to use the same techniques that I used in `StrBase.jl`, i.e. to align the pointer and only make aligned 4/8 byte loads that are guaranteed to be safe, and then mask / shift.

### CODE REVIEW

File: src/base.jl [hunk 1]
```diff
@@ -17,24 +18,54 @@ function check_size(T, sz)
...
 
-    # TODO some times this can throw errors for longish strings
-    # Exception: EXCEPTION_ACCESS_VIOLATION at 0x1e0b7afd -- bswap at C:\Users\RTX2080\.julia\packages\BitIntegers\xU40U\src\BitIntegers.jl:332 [inlined]
-    # ntoh at .\io.jl:541 [inlined]
-    content = (T(s |> pointer |> Ptr{T} |> unsafe_load |> ntoh) >> bits_to_wipe) << bits_to_wipe
-    ShortString{T}(content | T(sz))
+const CHUNKSZ   = sizeof(UInt)
+const CHUNKBITS = sizeof(UInt) == 4 ? 32 : 64
+
+@inline function _ss(::Type{T}, str::String, sz) where {T}
```
Comment (oxinabox) [inline src/base.jl:29]: Why not write:
```suggestion
@inline function _ss(T::Type, str::String, sz)
```

Also would be good with a docstring or a comment explaining what it is.

**Review by oxinabox — APPROVED** [review]

File: src/base.jl (hunk 1 above)
Comment (ScottPJones) [reply src/base.jl:29]: I originally just had `T`, but then worried that Julia might not specialize on that, didn't have the time to double check.
I'll had the docstring in the next PR!
